version: "3.4"

services:
  nginx:
    image: nginx:latest
    container_name: vietlabo-test-nginx
    depends_on:
      - app
    volumes:
      - ./:/var/www
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '${DOCKER_NGINX_EXTERNAL_PORT}:80'
    networks:
      - default
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: local
    container_name: vietlabo-test-app
    volumes:
      - ./:/var/www
    expose:
      - '9000'
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
      CONTAINER_ROLE: app
    networks:
      - default
  db:
      image: mariadb:10.4
      container_name: vietlabo-test-mysql
      ports:
          - '${DOCKER_MYSQL_EXTERNAL_PORT}:3306'
      environment:
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: 'vietlabo_test'
          MYSQL_USER: dev
          MYSQL_PASSWORD: 123456
          MYSQL_ROOT_PASSWORD: 123456
      volumes:
          - mysql-data:/var/lib/mysql/
      networks:
          - default
volumes:
  mysql-data:
     driver: local
networks:
 default:
     driver: bridge
